### ISSUE TITLE
Chrome Video Lag

### ISSUE THREAD

**Issue by Selindrile** [Windower/Lua#1520]
FFXI Dev version, when a video is playing on Google Chrome while FFXI is up, and my mouse moves across google Chrome, (Any instance of it.) the video lags and skips horribly (audio is fine).

When my mouse is moving over things that aren't google chrome, video is fine.
When my mouse moves over google chrome when FFXI is not up, video is fine.

**Comment by alphaONE2** [comment]
And you're saying it doesn't happen on live, or without Windower? I'm really not sure there's much we can do here. Chrome uses the GPU to render everything on the page, including the video. FFXI is also using the GPU to render. There's bound to be some contention over this limited resource. You might try [turning off hardware acceleration in chrome](http://www.pcadvisor.co.uk/how-to/internet/how-turn-off-gpu-hardware-acceleration-in-google-chrome-3605455/).

**Comment by Selindrile** [comment]
It didn't happen before the hook change, I turned off hardware acceleration, no effect.

And it can't just be the gpu right? It's literally only when moving the mouse OVER CHROME while playing the video IN CHROME with FFXI up, I can move the mouse over FFXI or any other application just fine and no video stutter, and yes, the stutter doesn't happen without FFXI up, it seems to be specifically between chrome and FFXI. 

The same videos do not lag in Internet Explorer  or Discord when I move the mouse anywhere, including over Chrome while watching the video in Internet Explorer or Discord with FFXI up.

I also tried disabling all my extensions on Chrome, no change.

**Comment by alphaONE2** [comment]
Moving the mouse within Chrome triggers redraws, so yes, it can really be that simple. Please confirm that it doesn't happen without Windower.

**Comment by Selindrile** [comment]
It didn't happen before latest hook and it doesn't happen with Ashita, which I used yesterday for augments (the only thing I use it for as I prefer the Oseem addon to MAGA), but I haven't tried it with Vanilla XI in windowed mode, will do so after what I'm working on.

However if it was extra strain on processor due to those redraws wouldn't that mean I'd lag if moving my mouse over chrome while playing the video in Internet Explorer or Discord? Which I mentioned I was doing with no lag. Or does it only do so while a video is playing in chrome and mousing over chrome.

**Comment by Selindrile** [comment]
It does indeed happen with vanilla windowed mode, so I guess it's yet another side effect of the new hook using that instead of faking the fullscreen mode... ugh... that's really, super annoying.... no idea why it doesn't happen with other video players even if I'm moving my mouse over Chrome, or in the faked fullscreen that Windower used to use and Ashita still does....

**Comment by Byrth** [comment]
We pushed a version that might address this.

As a reminder, you have to relog (from the launcher) for the new hook to take effect.

**Comment by z16** [comment]
As for me, this seems to have fixed it.

**Comment by alphaONE2** [comment]
Just to clarify, it's still a problem on SE's end, we've just worked around SE's bad code.

**Comment by Byrth** [comment]
This fix worked, but broke fishing. I've provided some dumps on IRC.

**Comment by Selindrile** [comment]
Still not fixed for me. :(

**Comment by z16** [comment]
Are you on version 4.3.0.5?

**Comment by Selindrile** [comment]
Yes, at least that's what it says when my Windower screen is loading, been using the dev version for many months.

Launcher: 4.3.6312.40615
Hook: 4.3.0.5

OS: Windows 7
Chrome: 58.0.3029.81 (64-bit)

**Comment by Selindrile** [comment]
Even when not watching a video, simply trying to load another webpage/scrolling around "freezes up" while moving my mouse across chrome with the new FFXI hook up.

**Comment by Selindrile** [comment]
And it seems to be fixed? Not sure what changed....

**Comment by Byrth** [comment]
I'll take it!

**Comment by Selindrile** [comment]
Not sure if I can reopen this, but it's back... :/

**Comment by Selindrile** [comment]
And it's gone again after latest update.
