### ISSUE TITLE
Boxdestroyer broken after Jan 2025 update

### ISSUE THREAD

**Issue by Neqsal** [Windower/Lua#2418]
Someone brought this to my attention asking if I could look at it. Its all out of whack. Seems IDs were changed? It cant guess right even if it was exactly what the first and second digits are.

**Comment by z16** [comment]
Fixed on dev, should go live soon.

**Comment by bassomitron** [comment]
Getting a new lua runtime error with the dev version on line 305 of boxdestroyer.lua: "attempt to index global 'offsets' (a nil value)"

**Comment by z16** [comment]
Thanks for mentioning it, should be fixed now.

**Comment by bassomitron** [comment]
This error comes back whenever I log back in after a session, but it appears immediately and says, "attempt to index global 'messages' (a nil value)". It goes away when I unload the addon, delete the "data" folder, and reload.

**Comment by Neqsal** [comment]
The issue bassomitron mentioned is still happening. Can the issue be reopened? @z16

**Comment by z16** [comment]
> The issue bassomitron mentioned is still happening. Can the issue be reopened? [@z16](https://github.com/z16)

Have you tried it on the dev release of Windower? It's only been solved there. If so, can you provide the exact error message?

You can either take a screenshot, or do `//console_log 1` and then load it, that will produce a `console.log` file in your Windower folder, the entire console log will be in there, you can just copy it from there.

**Comment by Neqsal** [comment]
I could of sworn this was happening on the dev launcher. Un momento..

Yes just loaded it on dev build and i get the error in the pic.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Neqsal** [comment]
Oh pic sent via email didnt show up.

Lua runtime error. Boxdestroyer.lua :313
Global ‘messages’ nil

Edit:
It just periodically spams that error. Boxes or not. Sorry being lazy using my phone

**Comment by Neqsal** [comment]
In the incoming packet event at that line it checks for an index for messages without checking ifessages is nil. It also makes that check without a id check so ita getting hit by any and every incoming packet im assuming

**Comment by z16** [comment]
I just pushed an update, someone else who experienced the error said that it fixed it for them. Can you try again now?

**Comment by bassomitron** [comment]
That seems to have fixed it for me. Thanks so much for all your hard work!
